
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dhea
 */
public class Frame2 extends javax.swing.JFrame {

    String str, str1;
    int choice, z, pin = 1234, a = 3;
    int t, s, tab = 0;
    
    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ATM Phew-Phew");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 80, 253, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 140, 253, 17);

        menu.setBackground(new java.awt.Color(255, 204, 204));
        menu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Satu --", "Info Saldo", "Tarik Tunai", "Setor Tunai", "Petunjuk", "Keluar" }));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu);
        menu.setBounds(120, 170, 150, 30);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 310);

        setSize(new java.awt.Dimension(399, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        setmenu();
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> menu;
    // End of variables declaration//GEN-END:variables

    private void setmenu() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (menu.getSelectedItem().equals("Info Saldo"))
        {
            this.setVisible(true);
            JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " + tab); //informasi saldo
            z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain ?","ATM Phew-Phew",
                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
            if (z==0)
            {
                this.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM Phew-Phew, ambil kartu ATM Anda.");
                System.exit(0);
            }
        }
        else if (menu.getSelectedItem().equals("Setor Tunai"))
        {
            this.setVisible(true);
            str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran : " ); //menabung
            s = Integer.parseInt(str1);
            setor hasil = new setor();
            hasil.menabung(tab, s);
            tab =hasil.getsaldo();
            z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain ?","ATM Phew-Phew",
                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
            if (z==0)
            {
                this.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM Phew-Phew, ambil kartu ATM Anda.");
                System.exit(0);
            }
        }
        else if (menu.getSelectedItem().equals("Tarik Tunai"))
        {
            this.setVisible(true);
            str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan
            t = Integer.parseInt(str1);
            tarik mengambil = new tarik();
            mengambil.ambil(tab,t);
            tab =mengambil.getsaldo();
            z=JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","ATM Phew-Phew",
                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
            if (z==0)
            {
                this.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM Phew-Phew, ambil kartu ATM Anda.");
                System.exit(0);
            }
        }
        else if (menu.getSelectedItem().equals("Petunjuk"))
        {
            z=JOptionPane.showConfirmDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan Uang sesuai kebutuhan dan rajinlah menabung\n ","INFO",
                JOptionPane.YES_NO_OPTION, 3); //konfirmasi transaksi lain
            if (z==0)
            {
                this.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM Phew-Phew, ambil kartu ATM Anda.");
                System.exit(0);
            }
        }
        else if (menu.getSelectedItem().equals("Keluar"))
        {
            JOptionPane.showMessageDialog(null,"SILAHKAN AMBIL KARTU ATM ANDA !","TERIMAKASIH",JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
    }
}
